services:
  mysql:
    image: mysql:8.0.34
    ports:
      - '3306:3306'
    volumes:
      - C:\\Users\\showj\\IdeaProjects\\sql\\schema\\schema.sql:/path/in/container/schema.sql
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass