name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_RANDOM_ROOT_PASSWORD=yes
          MYSQL_DATABASE=app
          MYSQL_USER=app
          MYSQL_PASSWORD=pass
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    steps:
      - name: Container start
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Waiting for container start
        run: sleep 30

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start application
        run: java -jar ./artifacts/app-deadline.jar &

      - name: Wait for application to start
        run: |
          for i in {1..30}; do
            if curl -s localhost:3306/app; then
              echo "Application is running"
              break
            fi
            echo "Waiting for application to start..."
            sleep 5
          done

      - name: Build with Gradle and run tests
        run: ./gradlew test --info